### ISSUE TITLE
config with empty sni not work!

### ISSUE THREAD

**Issue by GFW4Fun** [Surfboardv2ray/Xray-Load-Balancer#1]
Hi
If the TLS config is enabled and the SNI is null, the balancer will not work. The SNI value should be automatically fixed and taken from the host or configuration address if it is empty! 

Thank you.

**Comment by Surfboardv2ray** [comment]
> Hi If the TLS config is enabled and the SNI is null, the balancer will not work. The SNI value should be automatically fixed and taken from the host or configuration address if it is empty!
> 
> Thank you.

Hi, thanks for your feedback. As far as the rational way of configs go, TLS configs usually contain SNIs as well. But the issue you mentioned, relies on v2ray to json parser [v2tj.py](https://github.com/Surfboardv2ray/Xray-Load-Balancer/blob/main/v2tj.py). You could simply replace it with a more efficient json converter script for this matter.
